---
title: "hw-01"
author: "Dimitris Agouridis (S2731031)"
date: "10/10/2024"
output: html_document
---

```{r setup, include=FALSE}    
knitr::opts_chunk$set(out.width = "100%")
```


------------------------------------------------------------------------------

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)
```

```{r load-data, message=FALSE}
edibnb <- read_csv("data/edibnb.csv")
council <- read_csv("data/council_assessments.csv")
```

------------------------------------------------------------------------------


## EXERCISE 1

```{r hw1-ex1}
#Exercise 1a
calc_na <- is.na(edibnb)
  number_na <- colSums(calc_na)
    number_na
    
#Exercise 1b
edibnb %>%
  filter(review_scores_rating == 100) %>%
    arrange(desc(number_of_reviews)) %>%
      head(1)

```




The variables missing observations include Price, Neighbourhood, Bathrooms, Bedrooms, Beds, and Review Scores Rating.

Listing 860170, located in Old Town, has received the highest number of reviews with a perfect score.


------------------------------------------------------------------------------

## EXERCISE 2

```{r hw1-ex2}
#Exercise 2a
  price_oldtown <- edibnb %>%
    filter( price > 100) %>%
     filter( neighbourhood == "Old Town") 
       count <- count(price_oldtown)
         n_rows
    
#Exercise 2b
edibnb %>%
  filter(neighbourhood == "Southside") %>%
   filter(accommodates >= 4) %>%
    arrange(desc(price)) %>%
     head(1)

edibnb %>%
  filter(neighbourhood == "Southside") %>%
    filter(accommodates >= 4) %>%
      arrange(price) %>%
        head(1)

Southside <- edibnb %>%
  filter(neighbourhood == "Southside") %>%
    filter(accommodates >= 4)
  
Southside_mean <- mean(Southside$price, na.rm = TRUE) 
  Southside_mean
```


Old Town features 494 properties.

In Southside, the highest price is 800, while the lowest is 10. The average price for properties in this area is 153.14.

------------------------------------------------------------------------------

## EXERCISE 3

```{r hw1-ex3}

#Exercise 3a
Newington <- edibnb %>%
  filter(neighbourhood == "Newington") 
   
  frequency_table <- table(Newington$bathrooms)
  frequency_table
    
#Exercise 3b    
more_bathrooms_than_bedrooms <-edibnb %>%
   mutate(ceiling_bathrooms = ceiling(bathrooms)) %>%
    filter(ceiling_bathrooms > bedrooms)

      num_more_bathrooms_than_bedrooms <- count(more_bathrooms_than_bedrooms)
      num_more_bathrooms_than_bedrooms
  
```

Frequency table:

0     0.5       1     1.5      2       3     3.5 

1       3     348      48     34       3      1 

963 properties have more bathrooms than bedrooms.


------------------------------------------------------------------------------

## EXERCISE 4

```{r hw1-ex4}

#Exercise 4a
council$assessment_date <- dmy(council$assessment_date)
  sum(month(council$assessment_date) == 5)

#Exercise 4b

full <- full_join(edibnb, council, by = "id")
full["rating"][full["rating"] == "good"] <- "1"
full["rating"][full["rating"] == "adequate"] <- "1"
full["rating"][full["rating"] == "poor"] <- "1"

full$rating <- as.numeric(full$rating) 
ggplot(data = full) + 
       geom_col(mapping = aes(x = neighbourhood,
                              y = rating))+
       guides(x = guide_axis(angle = 45)) + 
       labs(x = "Neighbourhood", y = "Number of ratings",
       title ="Number of council ratings for each neighbourhoods in edinburgh",
       subtitle = "From the edibnb and council dataframes") + 
       theme(axis.title = element_text(face="bold")) 


```


There are 296 properties in May. Additionally, the council has mainly concentrated its efforts on properties in Leith, indicating that not all neighborhoods are being targeted equally by the government.


------------------------------------------------------------------------------
